### ISSUE TITLE
SIGPIPE stops server

### ISSUE THREAD

**Issue by OriginalNexus** [3labs/mouse-hacks#1]
When the client disconnects, the pipe is broken so when the server tries to write something, it receives `SIGPIPE`. This signal stops the program by default.
The server should run indefinitely and accept any number of clients. A fix wold be to catch the signal and move to the next client, disconnecting from the current one (which is dead).

**Comment by alexonea** [comment]
Handling signals is one aspect of the problem. Indeed, when SIGPIPE is received there is a possibility that one of the clients disconnected without notice but maybe there are some other reasons for the signal, some of which do not involve clients (maybe, only maybe). Then, handling multiple clients should be done via selects and fd sets. Have a look at the select function in C.

**Comment by OriginalNexus** [comment]
There are no multiple clients at the moment. The server takes care of one client at a time.
In a future release where maybe the server controls multiple clients simultaneously, we will probably need something else to figure out what caused a `SIGPIPE` (such as selects or forks).

**Comment by alexonea** [comment]
There should be a specific protocol between the client and the server based
on message IDs and timeouts. For example, the server might poll the client
every 30s and update its status (ONLINE/OFFLINE). If a poll fails i.e. the
client doesn't respond then it means it got disconnected. Otherwise the
client has to let the server know when it is about to disconnect.

Alexandru Onea

**Comment by OriginalNexus** [comment]
This is another good solution. Probably the best solution would be to have a timeout for `write` and `read` . I don't know if there is some sort of feature that enables this, basically making `write` and `read` timeout (return -1) after a certain amount of time.

**Comment by alexonea** [comment]
Again, have a look at the select function. It allows you to set timeouts
and to multiplex sockets :) Exactly what you want.

Alexandru Onea
